"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Sparkles, Utensils } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { draftDietPlan, saveDietPlan } from "@/actions/diet";

export function DietPlanForm({ consultationId }) {
  const [foodsToInclude, setFoodsToInclude] = useState("");
  const [foodsToAvoid, setFoodsToAvoid] = useState("");
  const [guidance, setGuidance] = useState("");
  const [aiGenerated, setAiGenerated] = useState(false);
  const [error, setError] = useState(null);
  const [drafting, setDrafting] = useState(false);
  const [saving, startSaveTransition] = useTransition();
  const router = useRouter();

  async function handleGenerateDraft() {
    setError(null);
    setDrafting(true);
    try {
      const draft = await draftDietPlan(consultationId);
      setFoodsToInclude(draft.foodsToInclude.join(", "));
      setFoodsToAvoid(draft.foodsToAvoid.join(", "));
      setGuidance(draft.guidance);
      setAiGenerated(true);
    } catch (err) {
      setError(err.message ?? "Failed to generate draft");
    } finally {
      setDrafting(false);
    }
  }

  function handleSubmit(e) {
    e.preventDefault();
    setError(null);
    startSaveTransition(async () => {
      try {
        await saveDietPlan({
          consultationId,
          foodsToInclude: foodsToInclude.split(",").map((s) => s.trim()).filter(Boolean),
          foodsToAvoid: foodsToAvoid.split(",").map((s) => s.trim()).filter(Boolean),
          guidance,
          aiGenerated,
        });
        router.refresh();
      } catch (err) {
        setError(err.message ?? "Failed to save diet plan");
      }
    });
  }

  return (
    <Card className="border-emerald-900/20">
      <CardHeader>
        <CardTitle className="flex items-center justify-between">
          <span className="flex items-center">
            <Utensils className="h-5 w-5 mr-2 text-emerald-400" />
            Diet Recommendations
          </span>
          <Button
            type="button"
            variant="outline"
            size="sm"
            onClick={handleGenerateDraft}
            disabled={drafting}
          >
            <Sparkles className="h-3.5 w-3.5 mr-1.5" />
            {drafting ? "Generating..." : "Generate draft with AI"}
          </Button>
        </CardTitle>
      </CardHeader>
      <CardContent>
        <form onSubmit={handleSubmit} className="space-y-4">
          {aiGenerated && (
            <p className="text-xs text-emerald-400 bg-emerald-950/30 border border-emerald-800 rounded-md px-3 py-2">
              This draft was generated by AI — review and edit before saving. It won't be
              shown to the patient until you save it.
            </p>
          )}

          <div className="space-y-1.5">
            <Label htmlFor="foodsToInclude">Foods to include</Label>
            <Textarea
              id="foodsToInclude"
              value={foodsToInclude}
              onChange={(e) => setFoodsToInclude(e.target.value)}
              placeholder="Comma-separated, e.g. plenty of water, oats, soft fruits"
              rows={2}
            />
          </div>

          <div className="space-y-1.5">
            <Label htmlFor="foodsToAvoid">Foods to avoid</Label>
            <Textarea
              id="foodsToAvoid"
              value={foodsToAvoid}
              onChange={(e) => setFoodsToAvoid(e.target.value)}
              placeholder="Comma-separated, e.g. spicy food, caffeine, alcohol"
              rows={2}
            />
          </div>

          <div className="space-y-1.5">
            <Label htmlFor="guidance">General guidance</Label>
            <Textarea
              id="guidance"
              value={guidance}
              onChange={(e) => setGuidance(e.target.value)}
              placeholder="Any additional guidance for the patient..."
              rows={3}
            />
          </div>

          {error && <p className="text-sm text-red-400">{error}</p>}

          <Button type="submit" disabled={saving} className="w-full">
            {saving ? "Saving..." : "Save Diet Plan"}
          </Button>
        </form>
      </CardContent>
    </Card>
  );
}
